# Numpy

**Numpy** is the shorting for **numerical python**.

## 1 What Is NumPy Arrays (Ndarrays)

- **Numpy array** is an important data structure for data science.
- **Array** is useful for **fast** and **efficient** numerical operations.
- **Numpy array** is **faster** than **built-in python** data structures.
- **Ndarray** is a common data structure for data analysis libraries and for machine learnings.

In [5]:
%timeit list(range(1000))

10.7 µs ± 81.3 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [2]:
import numpy as np

In [4]:
%timeit np.arange(1000)

1.25 µs ± 15.4 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [5]:
type(np.arange(1000))

numpy.ndarray

## 2 Create NumPy Arrays (Ndarrays)

In [6]:
a = np.random.randn(2, 3)
a

array([[-0.27494056, -0.5445613 ,  1.74272383],
       [-0.80737291, -0.03150095, -1.64888179]])

**ndim**: To check the **dimension** of the **array**

In [10]:
a.ndim

2

**shape**: To check the **shape** of the **array**

In [9]:
a.shape

(2, 3)

**dtype**: To check the **type** of the **array**

In [11]:
a.dtype

dtype('float64')

**array()**: To **convert** a **list** into **numpy array** 

In [13]:
list1 = [1, 2, 3, 4]

In [15]:
a = np.array(list1)
a

array([1, 2, 3, 4])

In [16]:
a.ndim

1

In [17]:
a.shape

(4,)

**zeros()**: To create a **numpy array** with certain size filled with **zeros**

In [20]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**ones()**: To create a **numpy array** with certain size filled with **ones**

**Note**: To create a **multi-dimensional numpy array** filled with **zeros (ones)**, you need to pass the **dimension** as a **tuple**

In [21]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])